name: Baseline
# Pull requests are judged by how they impact coverage and security.
# This sets the baseline so we can see the impact of each individual pull request by comparing it against main.

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Scala code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up JDK 15
      uses: actions/setup-java@v3.1.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Compile
      run: sbt compile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests
      run: sbt coverage test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Enforce coverage
      run: sbt coverageReport
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        flags: unittest
