name: Jobs PR Review

on: [pull_request]

jobs:
  build:
    name: Confirm that the fat jar builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up JDK 15
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Cache sbt packages
      uses: actions/cache@v3
      with:
        key: sbt_cache
        path: ~/.cache/coursier/v1/

    - name: Build jar
      run: sbt assembly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}