name: Deploy jobs fat jar

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up JDK 15
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Cache sbt packages
      uses: actions/cache@v2
      with:
        key: sbt_cache
        path: ~/.cache/coursier/v1/

    - name: Build jar
      run: sbt assembly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials for deployment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy Jobs fat jar to S3
      run: aws s3 cp target/scala-2.12/jobs.jar s3://foreign-language-reader-content/jobs.jar --acl public-read