name: Jobs PR Review

on: [pull_request]

jobs:
  build:
    name: Confirm that the fat jar builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Set up JDK 15
      uses: actions/setup-java@v3.4.0
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Cache sbt packages
      uses: actions/cache@v3.0.1
      with:
        key: sbt_cache
        path: ~/.cache/coursier/v1/

    - name: Build jar
      run: sbt assembly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  containers:
    name: Confirm the container builds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: Login to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build container
      run: |
        docker build . -t lkjaero/spark-runner:latest