name: Scala code test

on: [pull_request]

jobs:
  build:
    name: Confirm that the fat jar builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up JDK 15
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 15.0.1
          distribution: 'zulu'

      - name: Cache sbt packages
        uses: actions/cache@v3.0.5
        with:
          key: sbt_cache
          path: ~/.cache/coursier/v1/

      - name: Build jar
        run: sbt assembly

      - name: Build container
        run: |
          docker build . -t lkjaero/spark-runner:3.2.2
  
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        fetch-depth: '2'

    - name: Set up JDK 15
      uses: actions/setup-java@v3.4.1
      with:
        java-version: 15.0.1
        distribution: 'zulu'

    - name: Load SBT cache
      uses: coursier/cache-action@v6

    - name: Compile
      run: sbt compile

    - name: Run tests
      run: sbt coverage test

    - name: Enforce coverage
      run: sbt coverageReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        flags: unittest